### ISSUE TITLE
Set "native-modules": true, in elm-package.json

### ISSUE THREAD

**Issue by gabrielperales** [gabrielperales/elm-native-module#2]

**Comment by spookylukey** [comment]
Yep, was stuck on this missing bit in the instructions for quite a while! Thankfully some Googling revealed it eventually.

**Comment by gabrielperales** [comment]
Ops, I'm sorry about that. I must have done it time ago. Just today I was updating the tutorial, and I'm going to add a new example with a native function with 2 parameters, so it will be updated soon.

**Comment by gabrielperales** [comment]
@spookylukey I just have updated the code fixing this issue, and I have also added a new example of a native function with two parameters. Regards!

**Comment by spookylukey** [comment]
Thanks for the fix, and for the tutorial - it saved me a lot of work trying to convert some algorithmic code that was working fine in Javascript and would have been very difficult to convert to pure functional Elm while still achieving the performance I needed.

However, it would be great if the README could include the detail about needing to change your elm-package.json to include `"native-modules": true`.

Also, in my project, I found I sometimes I had problems with a 2-argument function working until I put `F2` on it, as per other places I've found on the internet. Did you not have the same problem?

**Comment by gabrielperales** [comment]
@spookylukey did you see the new example I have added? it is a function with 2 parameters, and I'm not using `F2`. Another thing, I'm not good writing in english, so if you have seen something I can improve, would you mind to do a pull request? Thank you.

**Comment by spookylukey** [comment]
@gabrielperales Thanks, I saw that example now. However, it's not a very natural way to do it IMO, and all the Elm core libraries use `F2`, `F3` etc.. So I've sent a pull request about that, and another one to document in the README the need for `native-modules: true`.

**Comment by gabrielperales** [comment]
@spookylukey thank you very much for your contribution :)
